### ISSUE TITLE
Pin the version of yiyunliu/liquid-benchmark

### ISSUE THREAD

**Issue by plredmond** [plum-umd/oopsla2020-artifact#2]
Currently the dockerfile clones `yiyunliu/liquid-benchmark@HEAD` which could be different at different times, and therefore not reliably build

https://github.com/plum-umd/oopsla2020-artifact/blob/a591a552f6938dc840ff44bbe2f47d4596af1a8f/Dockerfile#L8-L9

As a **final step** before submission this needs to be pinned to a known-good githash

**Comment by yiyunliu** [comment]
Pinned the version by adding the repo as a submodule. I believe it is better than pinning in the Dockerfile since we can now reference the files directly in the documentation using relative paths.
